### PR TITLE
Update firstPersonControls.js

### PR DESCRIPTION
**Pull request by Noctisdark**
move PI_2 from a local variable to a constant global variable, (Maybe we'll use that later)
remove upAxis and calculates some simple expression by hand
Anonymous function are slightly slower that regular functions (those who have names)
Simple optimizations regarding PhysiJS appyCentralImpulse ...
Added comments about things that should be reviewed ! such as delta variable

### CODE REVIEW

**Comment by sasha240100** [comment]
@Noctisdark add if statement
```javascript

if (window) {
  var MouseEvent = window.MouseEvent;
  // Polyfill code here
}

```
Try that. I think Travic-Ci won't fail now.

**Comment by sasha240100** [comment]
@Noctisdark  build fails on whitestorm.test.js.
Try to run `gulp build`

**Comment by sasha240100** [comment]
Some tips:
 - **Line 128**: New line after code block. Same on lines: **152, 159, 167, 168, 142, 11, 16, 5, 6**(https://github.com/WhitestormJS/whitestorm.js/blob/bcff0e8e7178e269cb8651badcb242e9c60e223a/src/libs/firstPersonControls.js#L128)
 - **Line 146**: Remove commented `console.log`. Same on lines: **171**(https://github.com/WhitestormJS/whitestorm.js/blob/bcff0e8e7178e269cb8651badcb242e9c60e223a/src/libs/firstPersonControls.js#L146)
 -  **Line 145**: Remove this line. (https://github.com/WhitestormJS/whitestorm.js/blob/bcff0e8e7178e269cb8651badcb242e9c60e223a/src/libs/firstPersonControls.js#L143)

**Comment by sasha240100** [comment]
@Noctisdark Fix travis-ci, fix my tips and update pull request. I will merge it!

**Comment by Noctisdark** [comment]
That did not work, I check even In the nodeJS console, If(window && 1) throw an error window is not defined

**Comment by sasha240100** [comment]
@Noctisdark I just found that you made a new branch `Engine Struct Improvements`. Please, ping all us when you create a new branch. Okay?) 

---

Okay, I'll take a look at your problem. Then we will merge it.

**Comment by Noctisdark** [comment]
In fact I did told you ^^ but no problem, I'll notify in main_dev

**Comment by sasha240100** [comment]
@Noctisdark I did not notice(
It's better to notify everybody in main_dev. Use `@channel` to notify all.

**Comment by Noctisdark** [comment]
Thanks ^^, for the API.def I made this method WHS.extend (turns out to be different from $.extend, I'll fix that if you will), that changes values that are not set to an object, I provided an example :)

**Comment by sasha240100** [comment]
@Noctisdark  Yep. That's fine. But `WHS.API.extend`, okay?:)

**Comment by Noctisdark** [comment]
Okay ^^, We need another to polyfill $.extend that actually replaces the values, and can be recursive

**Comment by sasha240100** [comment]
@Noctisdark I fixed that problem. Now i merge.

**Pull request merged**
