### PR TITLE
#136 - fixes left/right/top/bottom pan - thanks goes to @thejmazz

### PR DESCRIPTION
**Pull request by hirako2000**

### CODE REVIEW

**Comment by sasha240100** [comment]
@hirako2000 @thejmazz So it errored because of scope (arrow function) ?

**Comment by hirako2000** [comment]
looks like incorrect javascript to me. it doesn't error but doesn't execute a function. its invalid code. no idea how it got there. seems like auto generated by some tool.

**Comment by sasha240100** [comment]
@hirako2000 That was my rewriting of it to es6 😄

**Comment by hirako2000** [comment]
should I use this issue to reformat the code as well? it's not following whs code style at all.

**Comment by sasha240100** [comment]
@hirako2000 If you have a time - sure

**Comment by thejmazz** [comment]
@sasha240100 

It is not an issue of `this` scope from arrow functions; the functions were doing this:

```javascript
const panLeft = () => {
  const v = new Vector3();

  return function panLeft(distance, objectMatrix) {
    v.setFromMatrixColumn(objectMatrix, 0); // get X column of objectMatrix
    v.multiplyScalar(-distance);
    panOffset.add(v);
  };
};
```

instead of

```javascript
const panLeft = (() => {
  return (distance, objectMatrix) => {
  
  }
})()
```

which is an IIFE (immediately invoked function expression) for a function that returns another function.

Its very similar to a decorator, a decorator is basically the same thing but only for classes.

Without decorator:
```javascript
class MyClass extends Component {
  ...
}

export default myDecorator(...params)(MyClass)
```

with decorator:
```javascript
@myDecorator(...params)
export default class MyClass extends Component {
  ...
}
```

In the case with orbit controls, the "decorator" is an anonymous function and has no params, but uses `v` from within a closure.

The spec for decorator is still young (stage 2) and might change (or never get accepted). See [proposal-decorators](https://github.com/tc39/proposal-decorators).

**Comment by sasha240100** [comment]
@thejmazz Thanks for the explanation!

**Pull request merged**
