### PR TITLE
#215 - LoaderModule

### PR DESCRIPTION
**Pull request by sasha240100**
**This PR is related to issue #215**

### CODE REVIEW

**Comment by thejmazz** [comment]
Alex has explained to me this API, but I still do not fully grasp it, so I'd like to experiment with it first

(I think Alex and I see a little differently how to use `LoaderModule`)

And an example should probably be added before merging module into main branch, no?

**Comment by sasha240100** [comment]
@thejmazz Yes, totally forgot about example. I suggest making a scene with multiple objects loaded (and textures). And making a spinner that will fadeOut when scene is loaded.

**Comment by sasha240100** [comment]
@thejmazz Suggest the API you want to add/remove in the comments to this PR, or even better to do it with a review (request changes / comment)

**Comment by sasha240100** [comment]
@hirako2000 Waiting for your review

**Comment by hirako2000** [comment]
@thejmazz , can you play with this to confirm it works fine?

**Comment by thejmazz** [comment]
@hirako2000, yes, should have time this weekend

**Pull request merged**
