### PR TITLE
Fix Source Code links

### PR DESCRIPTION
**Pull request by shshaw**
Updated link to the Source Code from /beta/ branch to /dev/

### CODE REVIEW

**Review by hirako2000 — APPROVED** [review]

**Comment by hirako2000** [comment]
I thought I fixed that, but thanks @shshaw !

**Comment by sasha240100** [comment]
@hirako2000 @shshaw PR should point to `dev` branch, can't merge

**Comment by shshaw** [comment]
Apologies. Git is not one of my strengths. I believe I've changed that now, let me know if you need an adjustment.

**Comment by sasha240100** [comment]
@shshaw Thanks! Merged now.

**Pull request merged**
