### PR TITLE
Alpha network module

### PR DESCRIPTION
**Pull request by amitmeghare**

### CODE REVIEW

**Comment by sasha240100** [comment]
@TheCodeCrafter Could you please add an example / instruction how to run/test it?

**Comment by noahcoetsee** [comment]
Yes, I still have to finish the server (nodejs) part of it, and then it'll be good to go. I didn't mean to make it seem finished xD

**Comment by sasha240100** [comment]
@TheCodeCrafter What's the state of this PR? Is it finished?

**Review by noahcoetsee — COMMENTED** [review]
@sasha240100 I still need to work out the kinks with the server design.

**Comment by noahcoetsee** [comment]
This only has build conflicts. Can we just fix this?

**Comment by noahcoetsee** [comment]
I closed this PR because this branch is in no state to be requesting merges. It is still under _heavy_ development. Please don't PR a branch if you haven't worked on the branch and know of it's progress.

**Pull request closed without merging**
