### PR TITLE
PR for #318

### PR DESCRIPTION
**Pull request by hirako2000**
Fixes a few mesh parameter types.

### CODE REVIEW

**Review by ChaseWhite3 — APPROVED** [review]
sorry i didn't notice the geom

**Comment by noahcoetsee** [comment]
Just added a tag and assigned sasha, to see if he can take a look at it.

**Comment by hirako2000** [comment]
@TheCodeCrafter  this change is just to fix a few mistakes as we rushed through adding types for all the meshes a couple of months ago. This should fix `geometry` param that was misnamed `parameters`.

**Review by sasha240100 — APPROVED** [review]
Approve (know nothing about types:D)

**Comment by noahcoetsee** [comment]
So, I guess that means we need to merge? If both approve, then go ahead and merge, right?

**Review by noahcoetsee — APPROVED** [review]
I think these changes are fine.

**Pull request merged**
